
#-------------MES ROUTES-------------

rh.employe:
  resource: "@RH_EmployeBundle/Controller/"
  type:     annotation
  prefix:   /GRH


api_externe:
  resource: "@ApiExterneBundle/Controller/"
  type:     annotation
  prefix:   /apipr

groupe:
    resource: "@GroupeBundle/Controller/"
    type:     annotation
    prefix:   /gestion-groupe

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /menu-admin

fournisseur:
    resource: "@FournisseurBundle/Controller/"
    type:     annotation
    prefix:   /fournisseur

produit:
    resource: "@ProduitBundle/Controller/"
    type:     annotation
    prefix:   /produit

gestion:
    resource: "@GestionBundle/Controller/"
    type:     annotation
    prefix: /stock

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
